image: amazon/aws-cli
pipelines:
  branches:
    'build-docker-image':
      - step:
          runs-on:
            - 'self.hosted'
            - 'linux.arm64'
          name: build and publish docker image
          services:
            - docker
          script:
            - export REPO_NAME=registry-stage.qiscus.io/integration/
            - export PROJECT_NAME=windmill-custom
            - export IMAGE_TAG="${REPO_NAME}""${PROJECT_NAME}":"${BITBUCKET_BUILD_NUMBER}"
            - docker build -t ${IMAGE_TAG} -f DockerfileNginx
            - echo ${HARBOR_PASSWORD} | docker login registry-stage.qiscus.io --username ${HARBOR_USER} --password-stdin
            - docker push "${IMAGE_TAG}"
            - echo ${IMAGE_TAG}
options:
  docker: true

